CREATE TABLE IF NOT EXISTS public.catgame_high_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
  level INTEGER NOT NULL CHECK (level >= 1),
  food INTEGER NOT NULL CHECK (food >= 0),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.catgame_high_scores ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS públicas para un leaderboard
CREATE POLICY "Permitir lectura pública de puntajes" 
  ON public.catgame_high_scores FOR SELECT 
  TO anon, authenticated
  USING (true);

CREATE POLICY "Permitir inserción pública de puntajes" 
  ON public.catgame_high_scores FOR INSERT 
  TO anon, authenticated
  WITH CHECK (true);

-- Índice para optimizar consultas de ordenación
CREATE INDEX IF NOT EXISTS idx_catgame_high_scores_ranking 
  ON public.catgame_high_scores (level DESC, food DESC, created_at ASC);
